### ISSUE TITLE
Switch camera side on phone in the Room

### ISSUE THREAD

**Issue by dylan-13** [nexmo-se/video-express-react-app#97]
Hey ! I've forked your work and thank you very much you saved me a lot of time ! But I need to add a way to switch the camera side for phone users and I cant figure how I can do it.. 

Can you help me please ?

For the moment the only way is to leave the room and do it in waiting room, but in the room it dont recognize camera side

**Comment by rushil-v** [comment]
Hey..dylan.. Have you found out any solution for this ?
